# Generated by Django 5.0.4 on 2026-05-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='ABOUT OUR TRADING HUB', max_length=100)),
                ('title', models.CharField(default='Master the Markets with 5+ Years of Proven Expertise', max_length=200)),
                ('description', models.TextField(default='At Malonza Markets®, we combine cutting-edge strategies with psychological mastery to create disciplined traders.')),
                ('experience_years', models.IntegerField(default=5)),
                ('phone_number', models.CharField(default='+254 703 987 878', max_length=20)),
                ('phone_label', models.CharField(default='Ready to start?', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('telegram_link', models.URLField(default='https://t.me/malonzamarkets')),
                ('whatsapp_link', models.URLField(default='https://wa.me/254703987878')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='BotPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('botId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(blank=True, max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='brokers/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='brokers/qr/')),
                ('link', models.URLField()),
                ('button_text', models.CharField(default='Start Trading', max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('package', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('read', 'Read'), ('replied', 'Replied')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('reply_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('priceusd', models.FloatField(default=0.0)),
                ('pricekes', models.FloatField(default=0.0)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='courses/')),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoursePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('courseId', models.IntegerField()),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fa-users', 'Users Icon'), ('fa-check', 'Check Icon'), ('fa-trophy', 'Trophy Icon')], default='fa-users', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fact',
                'verbose_name_plural': 'Facts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fas fa-user-tie', 'Expertise'), ('fas fa-users', 'Community'), ('fas fa-tree', 'Growth'), ('fa fa-phone-alt', 'Support')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_1', models.CharField(default='Systematic Trading Approach', max_length=200)),
                ('subtitle_1', models.CharField(default='QUANTITATIVE · SYSTEMATIC · RULE-BASED', max_length=200)),
                ('description_1', models.TextField(default='Data analysis · Statistical modeling · Predefined execution rules')),
                ('button1_text_1', models.CharField(default='Get Free Signals', max_length=50)),
                ('button2_text_1', models.CharField(default='Learn More', max_length=50)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('title_2', models.CharField(default='Disciplined Execution', max_length=200)),
                ('subtitle_2', models.CharField(default='RISK MANAGEMENT · STRUCTURED EXPOSURE', max_length=200)),
                ('description_2', models.TextField(default='Controlled position sizing · Continuous evaluation · Repeatable processes')),
                ('button1_text_2', models.CharField(default='Join Free Telegram', max_length=50)),
                ('button2_text_2', models.CharField(default='Our Strategy', max_length=50)),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('price_usd', models.FloatField()),
                ('price_kes', models.FloatField(default=0)),
                ('period', models.CharField(default='/month', max_length=50)),
                ('features', models.TextField(help_text='Enter each feature on a new line')),
                ('is_popular', models.BooleanField(default=False)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('fas fa-newspaper', 'Newspaper'), ('fas fa-broadcast-tower', 'Broadcast'), ('fas fa-crown', 'Crown'), ('fas fa-chalkboard-teacher', 'Teacher'), ('fas fa-copy', 'Copy'), ('fas fa-chart-line', 'Chart')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price_text', models.CharField(default='FREE', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicePayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(max_length=100)),
                ('userId', models.IntegerField()),
                ('amountkes', models.FloatField(default=0.0)),
                ('amountusd', models.FloatField(default=0.0)),
                ('mpesa_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(default='initialized', max_length=20)),
                ('payment_method', models.CharField(default='mpesa', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Malonza Markets', max_length=100)),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('footer_text', models.TextField(default="Welcome to Malonza Markets® where Africa's top traders gather...")),
                ('copyright_text', models.CharField(default='© Malonza Markets®. All Rights Reserved.', max_length=200)),
                ('disclaimer_text', models.TextField(default='Disclaimer: Malonza is not a certified financial advisor...')),
                ('contact_email', models.EmailField(default='malonzanicholas@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='+254703987878', max_length=20)),
                ('contact_address', models.CharField(default='Nairobi, Kenya', max_length=200)),
                ('support_response_time', models.CharField(default='Reply within 24 hours', max_length=100)),
                ('support_phone_available', models.CharField(default='24 hrs telephone support', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('username', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('role', models.CharField(default='Student', max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('image', models.ImageField(upload_to='bots/')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trading Bot',
                'verbose_name_plural': 'Trading Bots',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Paste full YouTube URL (e.g., https://www.youtube.com/watch?v=... )', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('use_custom_thumbnail', models.BooleanField(default=False, help_text='Use custom uploaded thumbnail instead of YouTube default')),
                ('custom_thumbnail', models.ImageField(blank=True, help_text='Upload a custom thumbnail image', null=True, upload_to='video_thumbnails/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBotAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tradingbot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.siteusers')),
            ],
            options={
                'unique_together': {('user', 'bot')},
            },
        ),
        migrations.CreateModel(
            name='UserCourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.siteusers')),
            ],
            options={
                'unique_together': {('user', 'course')},
            },
        ),
    ]
