# Generated by Django 5.0.4 on 2026-05-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_win_rate', models.FloatField(default=78.5, help_text='Overall win rate percentage')),
                ('weekly_win_rate', models.FloatField(default=82.3, help_text='Weekly win rate percentage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Performance Stat',
                'verbose_name_plural': 'Performance Stats',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, help_text='Select videos for this course', to='myapp.video'),
        ),
        migrations.AddField(
            model_name='tradingbot',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload PDF file for the bot', null=True, upload_to='bot_pdfs/'),
        ),
    ]
