# Generated by Django 5.0.4 on 2026-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_performancestats_course_videos_tradingbot_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4, WebM, or OGG video file', null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video File')], default='youtube', help_text='Choose video source', max_length=10),
        ),
        migrations.AlterField(
            model_name='video',
            name='use_custom_thumbnail',
            field=models.BooleanField(default=False, help_text='Use custom uploaded thumbnail instead of default'),
        ),
    ]
