# Generated by Django 5.0.4 on 2026-05-21 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_video_video_file_video_video_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='videos',
        ),
        migrations.AlterField(
            model_name='video',
            name='custom_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='use_custom_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload MP4, WebM, or OGG video file', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste full YouTube URL', null=True),
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube Link'), ('upload', 'Upload Video File')], default='youtube', max_length=10)),
                ('video_url', models.URLField(blank=True, help_text='YouTube URL for this lesson', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4 video file for this lesson', null=True, upload_to='course_videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_videos', to='myapp.course')),
            ],
            options={
                'verbose_name': 'Course Video',
                'verbose_name_plural': 'Course Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
