# Generated by Django 5.0.4 on 2026-05-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_course_videos_alter_video_custom_thumbnail_and_more'),
    ]

    operations = [
    ]
