# Generated by Django 5.0.4 on 2026-05-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_initial_'),
    ]

    operations = [
        migrations.AddField(
            model_name='botpayments',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='botpayments',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='botpayments',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursepayments',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='coursepayments',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coursepayments',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicepayments',
            name='channel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicepayments',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servicepayments',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='botpayments',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursepayments',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coursepayments',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursepayments',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepayments',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='servicepayments',
            name='payment_method',
            field=models.CharField(default='paystack', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicepayments',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
